[2022-03-21 22:48:04,913] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:48:04,941] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:48:04,942] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:48:04,944] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 22:48:04,945] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:48:04,964] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 22:48:04,972] {standard_task_runner.py:52} INFO - Started process 879 to run task
[2022-03-21 22:48:04,985] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpzrlv3kiv', '--error-file', '/tmp/tmpzb0n52ao']
[2022-03-21 22:48:04,987] {standard_task_runner.py:77} INFO - Job 530: Subtask download_dataset_task
[2022-03-21 22:48:05,084] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 22:48:05,151] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 22:48:05,191] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 22:48:05,194] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 22:48:05,196] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-21 22:48:05,213] {subprocess.py:85} INFO - Output:
[2022-03-21 22:49:33,329] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 22:49:33,456] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220321T224804, end_date=20220321T224933
[2022-03-21 22:49:33,527] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 22:49:33,584] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-21 22:58:35,774] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:58:35,793] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:58:35,794] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:58:35,795] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 22:58:35,796] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:58:35,817] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 22:58:35,827] {standard_task_runner.py:52} INFO - Started process 1419 to run task
[2022-03-21 22:58:35,836] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '550', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpjaup9l6m', '--error-file', '/tmp/tmprbsocv34']
[2022-03-21 22:58:35,838] {standard_task_runner.py:77} INFO - Job 550: Subtask download_dataset_task
[2022-03-21 22:58:35,939] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 22:58:35,991] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 22:58:36,021] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 22:58:36,024] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 22:58:36,026] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-21 22:58:36,049] {subprocess.py:85} INFO - Output:
[2022-03-21 22:59:52,672] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 22:59:52,771] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220321T225835, end_date=20220321T225952
[2022-03-21 22:59:52,872] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 22:59:52,922] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:26:57,632] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:26:57,660] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:26:57,662] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:26:57,663] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:26:57,664] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:26:57,685] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 23:26:57,696] {standard_task_runner.py:52} INFO - Started process 2916 to run task
[2022-03-21 23:26:57,707] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpkzg26pq4', '--error-file', '/tmp/tmp3ltqx341']
[2022-03-21 23:26:57,710] {standard_task_runner.py:77} INFO - Job 604: Subtask download_dataset_task
[2022-03-21 23:26:57,823] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:26:57,895] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:26:57,939] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 23:26:57,941] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 23:26:57,944] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-21 23:26:57,994] {subprocess.py:85} INFO - Output:
[2022-03-21 23:27:47,677] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 23:27:47,788] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220321T232657, end_date=20220321T232747
[2022-03-21 23:27:47,878] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:27:47,937] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:03:09,232] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 09:03:09,244] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 09:03:09,245] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:03:09,245] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:03:09,246] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:03:09,263] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-23 09:03:09,272] {standard_task_runner.py:52} INFO - Started process 969 to run task
[2022-03-23 09:03:09,275] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '683', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpfcqzfiz2', '--error-file', '/tmp/tmpbfthzlvg']
[2022-03-23 09:03:09,277] {standard_task_runner.py:77} INFO - Job 683: Subtask download_dataset_task
[2022-03-23 09:03:09,344] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:03:09,386] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:03:09,408] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-23 09:03:09,410] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 09:03:09,411] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-23 09:03:09,426] {subprocess.py:85} INFO - Output:
[2022-03-23 09:05:00,100] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 09:05:00,160] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220323T090309, end_date=20220323T090500
[2022-03-23 09:05:00,267] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:05:00,392] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 15:39:10,487] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 15:39:10,516] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 15:39:10,518] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 15:39:10,519] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 15:39:10,521] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 15:39:10,555] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-23 15:39:10,574] {standard_task_runner.py:52} INFO - Started process 2554 to run task
[2022-03-23 15:39:10,597] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '915', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpf1cy2agd', '--error-file', '/tmp/tmp15v2q2hk']
[2022-03-23 15:39:10,602] {standard_task_runner.py:77} INFO - Job 915: Subtask download_dataset_task
[2022-03-23 15:39:10,742] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 15:39:10,834] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 15:39:10,886] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-23 15:39:10,894] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 15:39:10,909] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-23 15:39:10,951] {subprocess.py:85} INFO - Output:
[2022-03-23 15:40:14,684] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 15:40:14,744] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220323T153910, end_date=20220323T154014
[2022-03-23 15:40:14,799] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 15:40:14,861] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:04:27,935] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 16:04:27,947] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 16:04:27,948] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:04:27,949] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:04:27,950] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:04:27,961] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-23 16:04:27,967] {standard_task_runner.py:52} INFO - Started process 3978 to run task
[2022-03-23 16:04:27,972] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpgmd7khze', '--error-file', '/tmp/tmpniri80b7']
[2022-03-23 16:04:27,973] {standard_task_runner.py:77} INFO - Job 986: Subtask download_dataset_task
[2022-03-23 16:04:28,040] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:04:28,082] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:04:28,104] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-23 16:04:28,105] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 16:04:28,107] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-23 16:04:28,123] {subprocess.py:85} INFO - Output:
[2022-03-23 16:06:00,839] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 16:06:00,870] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220323T160427, end_date=20220323T160600
[2022-03-23 16:06:00,909] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:06:00,952] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 10:45:25,843] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 10:45:25,863] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 10:45:25,864] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:45:25,866] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 10:45:25,866] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:45:25,888] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-26 10:45:25,901] {standard_task_runner.py:52} INFO - Started process 5796 to run task
[2022-03-26 10:45:25,917] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '1338', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpxg4zximv', '--error-file', '/tmp/tmpwshart17']
[2022-03-26 10:45:25,920] {standard_task_runner.py:77} INFO - Job 1338: Subtask download_dataset_task
[2022-03-26 10:45:26,054] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 10:45:26,139] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 10:45:26,177] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-26 10:45:26,181] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 10:45:26,183] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-26 10:45:26,202] {subprocess.py:85} INFO - Output:
[2022-03-26 10:47:09,385] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-03-26 10:47:09,389] {subprocess.py:93} INFO - Command exited with return code 56
[2022-03-26 10:47:09,416] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-26 10:47:09,435] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220326T104525, end_date=20220326T104709
[2022-03-26 10:47:09,471] {standard_task_runner.py:92} ERROR - Failed to execute job 1338 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-26 10:47:09,512] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-26 10:47:09,587] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:32:47,277] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 15:32:47,292] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 15:32:47,294] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:32:47,295] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:32:47,296] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:32:47,310] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-03-26 15:32:47,318] {standard_task_runner.py:52} INFO - Started process 20251 to run task
[2022-03-26 15:32:47,330] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '1592', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpwnumemcz', '--error-file', '/tmp/tmpxscg8okg']
[2022-03-26 15:32:47,331] {standard_task_runner.py:77} INFO - Job 1592: Subtask download_dataset_task
[2022-03-26 15:32:47,422] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:32:47,490] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:32:47,542] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-26 15:32:47,546] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 15:32:47,547] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip > /opt/***/201901-citibike-tripdata.csv.zip']
[2022-03-26 15:32:47,572] {subprocess.py:85} INFO - Output:
[2022-03-26 15:33:01,638] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 15:33:01,752] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20220326T153247, end_date=20220326T153301
[2022-03-26 15:33:01,845] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:33:02,112] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
