[2022-03-21 23:19:08,194] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-21 23:19:08,209] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-21 23:19:08,210] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:19:08,211] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:19:08,212] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:19:08,229] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-21 23:19:08,239] {standard_task_runner.py:52} INFO - Started process 2437 to run task
[2022-03-21 23:19:08,245] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '580', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpvmnfy9m1', '--error-file', '/tmp/tmp61ur_5cy']
[2022-03-21 23:19:08,246] {standard_task_runner.py:77} INFO - Job 580: Subtask download_dataset_task
[2022-03-21 23:19:08,310] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:19:08,348] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:19:08,372] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-21 23:19:08,373] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 23:19:08,375] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-21 23:19:08,391] {subprocess.py:85} INFO - Output:
[2022-03-21 23:21:17,803] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 23:21:17,952] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220321T231908, end_date=20220321T232117
[2022-03-21 23:21:18,068] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:21:18,178] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:34:51,696] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-21 23:34:51,716] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-21 23:34:51,717] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:34:51,718] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:34:51,719] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:34:51,744] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-21 23:34:51,758] {standard_task_runner.py:52} INFO - Started process 3374 to run task
[2022-03-21 23:34:51,763] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '631', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp1a1yix18', '--error-file', '/tmp/tmp4sf9s17_']
[2022-03-21 23:34:51,765] {standard_task_runner.py:77} INFO - Job 631: Subtask download_dataset_task
[2022-03-21 23:34:51,849] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:34:51,903] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:34:51,935] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-21 23:34:51,939] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 23:34:51,941] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-21 23:34:51,965] {subprocess.py:85} INFO - Output:
[2022-03-21 23:36:08,867] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-03-21 23:36:08,870] {subprocess.py:93} INFO - Command exited with return code 56
[2022-03-21 23:36:08,886] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-21 23:36:08,899] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220321T233451, end_date=20220321T233608
[2022-03-21 23:36:08,917] {standard_task_runner.py:92} ERROR - Failed to execute job 631 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-21 23:36:08,945] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:36:08,983] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:10:51,806] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-23 09:10:51,818] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-23 09:10:51,819] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:10:51,819] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:10:51,820] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:10:51,831] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-23 09:10:51,840] {standard_task_runner.py:52} INFO - Started process 1488 to run task
[2022-03-23 09:10:51,844] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '713', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpi_agnz04', '--error-file', '/tmp/tmpiopydqv6']
[2022-03-23 09:10:51,845] {standard_task_runner.py:77} INFO - Job 713: Subtask download_dataset_task
[2022-03-23 09:10:51,910] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:10:51,950] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:10:51,971] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-23 09:10:51,973] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 09:10:51,974] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-23 09:10:51,987] {subprocess.py:85} INFO - Output:
[2022-03-23 09:12:58,740] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 09:12:58,815] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220323T091051, end_date=20220323T091258
[2022-03-23 09:12:58,888] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:12:58,955] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:20:55,490] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-23 16:20:55,504] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-23 16:20:55,506] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:20:55,507] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:20:55,509] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:20:55,523] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-23 16:20:55,533] {standard_task_runner.py:52} INFO - Started process 4978 to run task
[2022-03-23 16:20:55,537] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '1033', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpuh4d2ml5', '--error-file', '/tmp/tmp6ocoaljp']
[2022-03-23 16:20:55,539] {standard_task_runner.py:77} INFO - Job 1033: Subtask download_dataset_task
[2022-03-23 16:20:55,613] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:20:55,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:20:55,682] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-23 16:20:55,684] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 16:20:55,686] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-23 16:20:55,702] {subprocess.py:85} INFO - Output:
[2022-03-23 16:24:33,988] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 16:24:34,150] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220323T162055, end_date=20220323T162434
[2022-03-23 16:24:34,200] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:24:34,239] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 11:08:55,514] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-26 11:08:55,527] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-26 11:08:55,529] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:08:55,529] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 11:08:55,530] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:08:55,543] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-26 11:08:55,549] {standard_task_runner.py:52} INFO - Started process 7105 to run task
[2022-03-26 11:08:55,554] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '1388', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp1nnx8x_h', '--error-file', '/tmp/tmpqaut21hp']
[2022-03-26 11:08:55,556] {standard_task_runner.py:77} INFO - Job 1388: Subtask download_dataset_task
[2022-03-26 11:08:55,631] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 11:08:55,704] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 11:08:55,726] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-26 11:08:55,728] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 11:08:55,735] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-26 11:08:55,753] {subprocess.py:85} INFO - Output:
[2022-03-26 11:15:32,999] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 11:15:33,036] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220326T110855, end_date=20220326T111533
[2022-03-26 11:15:33,097] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 11:15:33,145] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:38:51,693] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-26 15:38:51,706] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-03-26 15:38:51,707] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:38:51,708] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:38:51,709] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:38:51,722] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2022-03-26 15:38:51,729] {standard_task_runner.py:52} INFO - Started process 20676 to run task
[2022-03-26 15:38:51,734] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '1623', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpf_xcy3g7', '--error-file', '/tmp/tmpv0wx6dm1']
[2022-03-26 15:38:51,735] {standard_task_runner.py:77} INFO - Job 1623: Subtask download_dataset_task
[2022-03-26 15:38:51,810] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:38:51,871] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:38:51,903] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-03-26 15:38:51,905] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 15:38:51,907] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip > /opt/***/201909-citibike-tripdata.csv.zip']
[2022-03-26 15:38:51,926] {subprocess.py:85} INFO - Output:
[2022-03-26 15:39:26,159] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 15:39:26,201] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20220326T153851, end_date=20220326T153926
[2022-03-26 15:39:26,248] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:39:26,296] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
